endpoints:
  styles:
    delete_when_any:
      - field: active
        equals: false
  colorways:
    delete_when_any:
      - field: active
        equals: false
  collections:
    delete_when_any:
      - field: active
        equals: false
  category1s:
    delete_when_any:
      - field: active
        equals: false
  category2s:
    delete_when_any:
      - field: active
        equals: false
  sizes:
    delete_when_any:
      - field: active
        equals: false
  apparel_dimensions:
    delete_when_any:
      - field: active
        equals: false
  seasons:
    delete_when_any:
      - field: active
        equals: false
  materials:
    delete_when_any:
      - field: active
        equals: false
  bom_masters:
    delete_when_any:
      - field: active
        equals: false
  bom_subtypes:
    delete_when_any:
      - field: active
        equals: false
  boms:
    delete_when_any:
      - field: active
        equals: false
  bom_sections: {}
  bom_lines:
    delete_when_any:
      - field: active
        equals: false
  supplier_quote_masters:
    delete_when_any:
      - field: active
        equals: false
  supplier_quotes:
    delete_when_any:
      - field: active
        equals: false
  suppliers:
    delete_when_any:
      - field: active
        equals: false
  factories:
    delete_when_any:
      - field: active
        equals: false
  color_specifications:
    delete_when_any:
      - field: active
        equals: false
  compositions:
    delete_when_any:
      - field: ok_for_material
        equals: false
  material_compositions:
    delete_when_any:
      - field: active
        equals: false
  care_symbols:
    delete_when_any:
      - field: active
        equals: false
  countries:
    delete_when_any:
      - field: active
        equals: false
  shipping_ports:
    delete_when_any:
      - field: active
        equals: false
  lookup_items:
    delete_when_any:
      - field: active
        equals: false
  lookup_item_subtypes:
    delete_when_any:
      - field: active
        equals: false
  material_types:
    delete_when_any:
      - field: active
        equals: false
  style_types:
    delete_when_any:
      - field: active
        equals: false
  product_sources:
    delete_when_any:
      - field: active
        equals: false
  routings: {}
  routing_items: {}
  routing_revisions: {}
  documents:
    delete_when_any:
      - field: active
        equals: false
  document_revisions:
    delete_when_any:
      - field: active
        equals: false
  duty_rates:
    delete_when_any:
      - field: active
        equals: false
  users:
    delete_when_any:
      - field: active
        equals: false
