version: 1

jobs:
  - name: material-create
    title: Material Create
    method: POST
    path: /v2/materials
    input:
      header_row: 1
    columns:
      code:
        header: Code
        headers:
          - Material Code
        type: text
        required: true
      product_type:
        header: Product Type
        headers:
          - Material Type
          - Type
        type: ref
        required: true
        resolve:
          endpoint: material_types
          match: node_name
          output: id
          filters:
            available: true
      description:
        header: Description
        headers:
          - Desc
        type: text
    body:
      code: code
      product_type: product_type
      description: description

  - name: material-composition-create
    title: Material Composition Create
    method: POST
    path: /v2/materials/{material}/technical_compositions
    input:
      header_row: 1
    columns:
      material:
        header: Material
        headers:
          - Material ID
          - Material Id
          - Material Code
          - Code
        type: ref_or_id
        required: true
        resolve:
          endpoint: materials
          match: code
          output: id
      compositions:
        header: Composition
        headers:
          - Technical Composition
          - Material Composition
          - Fiber Content
          - Content
        type: composition_list
        required: true
        resolve:
          endpoint: compositions
          match: node_name
          output: id
          filters:
            active: true
    body: compositions
